### ISSUE TITLE
Error making amm swap

### ISSUE THREAD

**Issue by jaimebanos** [raydium-io/raydium-library#11]
I'm trying to make a amm swap like in the example and with the cli and both result in "thread 'main' panicked at /home/juan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.19.0/src/internal.rs:33:3: from_bytes>SizeMismatch".

I guess its the wallet path, I'm using the file that solana-keygen new spits and it doesn't work, what could I be doing wrong?

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Raydium SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by FixResolution** [comment]
> I'm trying to make a amm swap like in the example and with the cli and both result in "thread 'main' panicked at /home/juan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.19.0/src/internal.rs:33:3: from_bytes>SizeMismatch".
> 
> I guess its the wallet path, I'm using the file that solana-keygen new spits and it doesn't work, what could I be doing wrong?

Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Denmal1982** [comment]
have you managed to figure out this error?
